# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


POST http://localhost:3000/albums
Content-Type: application/json

{"album_id":4,
  "album_name":"albumname4",
  "issue_date":"2019-1-1",
  "photo": "/photo/1.jpg",
  "singers": [
    {"singer_id":34,"singer_name":"Singer Name"}
  ],
  "company" : "测试照片公司",
  "comment": "测试备注",
  "songs": [{"song_id":23,"song_name":"我是一只小小鸟","time": 180}]
}

###

GET http://localhost:3000/albums
Accept: application/json

###

GET http://localhost:3000/albums/1
Accept: application/json

###
DELETE http://localhost:3000/albums/1
Accept: application/json

###