# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


POST http://localhost:3000/singers
Content-Type: application/json

{
  "singer_id":1,
  "singer_name":"singername1",
  "area":"上海",
  "birthday" : "1990-1-1",
  "sex": true,
  "photo": "/singerpic/1.jpg",
  "comment":"Test Comment"
}

###

PUT http://localhost:3000/singers
Content-Type: application/json

{
  "singer_id":1,
  "singer_name":"changed name",
  "area":"北京",
  "birthday" : "1990-1-2",
  "sex": true,
  "photo": "/singerpic/1.jpg",
  "comment":"Test Comment2"
}

###

GET http://localhost:3000/singers
Accept: application/json

###

GET http://localhost:3000/singers/2
Accept: application/json

###

DELETE http://localhost:3000/singers/1
Accept: application/json

###