# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


POST http://localhost:3000/users
Content-Type: application/json

{
  "user_id":1,
  "user_name":"username",
  "photo": "users/1.jpg",
  "password": "password",
  "real_name": "张三",
  "mobile": "18612345678",
  "email": "test@mycompany.com",
  "role_id": "admin"
}

###

GET http://localhost:3000/users
Accept: application/json

###


DELETE http://localhost:3000/users/1
Accept: application/json

###